# Generated by Django 2.0.5 on 2018-05-16 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barCode', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('createdOn', models.DateTimeField(blank=True)),
                ('canceledOn', models.DateTimeField(blank=True)),
                ('deactivatedOn', models.DateTimeField(blank=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('provider', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form', models.CharField(default='Unit', max_length=50)),
                ('totalUnitsInFromSale', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Deactivated', max_length=30)),
                ('promotion', models.CharField(default='No', max_length=3)),
                ('promotionStartsOn', models.DateTimeField(blank=True)),
                ('promotionExpiresOn', models.DateTimeField(blank=True)),
                ('formSale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.SaleForm')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('minAmountAlertForRestock', models.FloatField(default=0.0)),
                ('expirationDate', models.DateTimeField(blank=True)),
                ('boughtPrice', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
                ('salePrice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.SalePrice')),
            ],
        ),
    ]
